feat(codecommit): add template
gofireflyio/cf-templates pull request #29
Opened 2023-03-23 15:19 UTC by gmatang

2023-03-30 10:53 UTC, YuvalFireFly requested changes

2023-03-30 10:53 UTC, YuvalFireFly commented on aws_codecommit_template/template.yml
> +              - 'arn:aws:codecommit:*:111062076341:*'
Use AWS::AccountId

2023-04-09 09:48 UTC, YuvalFireFly approved these changes

2023-04-09 09:51 UTC, gilcoh33 approved these changes

2023-04-09 11:21 UTC, apetesh approved these changes

2023-04-10 08:15 UTC, merged